In [12]:
# Импортируем библиотеку pandas

import pandas as pd

In [13]:
# Загружаем исходные данные

df = pd.read_csv('XYZ input.csv', delimiter=';')
df

,product,income1,income2,income3,income4,income5,income6,income7,income8,income9,income10,income11,income12
0,product1,90,56,78,76,79,76,89,78,90,67,93,99
1,product2,1,45,7,68,98,65,4,32,56,78,98,8
2,product3,45,67,54,43,45,56,76,58,65,32,9,76
3,product4,9,9,9,9,9,9,9,9,9,9,9,9
4,product5,23,43,23,27,48,36,34,27,19,43,23,22
5,product6,98,99,90,97,90,98,97,99,97,97,99,90
6,product7,56,78,76,34,65,78,29,83,46,89,64,22
7,product8,48,6,64,4,74,61,40,96,23,39,36,90
8,product9,55,39,81,93,69,40,41,19,36,57,59,48
9,product10,54,45,50,38,52,80,29,54,12,93,75,23
10,product11,30,25,25,96,79,91,9,67,10,83,16,58
11,product12,99,74,53,68,81,83,17,25,13,70,75,11
12,product13,23,95,79,41,77,99,97,11,16,39,56,49
13,product14,93,98,68,95,32,22,53,86,53,79,49,37
14,product15,93,4,98,81,10,92,29,47,15,80,30,5
15,product16,66,26,75,9,86,41,17,40,90,5,94,22
16,product17,98,38,32,56,68,44,69,51,71,25,98,24
17,product18,25,29,30,15,40,43,25,27,20,30,28,23
18,product19,13,7,56,52,60,72,54,8,9,89,34,33
19,product20,24,91,47,97,23,59,32,27,9,66,47,33

In [14]:
# Сохраняем транспонированную таблицу для вычислений

df_t = df.transpose()
df_t

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
product,product1,product2,product3,product4,product5,product6,product7,product8,product9,product10,product11,product12,product13,product14,product15,product16,product17,product18,product19,product20
income1,90,1,45,9,23,98,56,48,55,54,30,99,23,93,93,66,98,25,13,24
income2,56,45,67,9,43,99,78,6,39,45,25,74,95,98,4,26,38,29,7,91
income3,78,7,54,9,23,90,76,64,81,50,25,53,79,68,98,75,32,30,56,47
income4,76,68,43,9,27,97,34,4,93,38,96,68,41,95,81,9,56,15,52,97
income5,79,98,45,9,48,90,65,74,69,52,79,81,77,32,10,86,68,40,60,23
income6,76,65,56,9,36,98,78,61,40,80,91,83,99,22,92,41,44,43,72,59
income7,89,4,76,9,34,97,29,40,41,29,9,17,97,53,29,17,69,25,54,32
income8,78,32,58,9,27,99,83,96,19,54,67,25,11,86,47,40,51,27,8,27
income9,90,56,65,9,19,97,46,23,36,12,10,13,16,53,15,90,71,20,9,9
income10,67,78,32,9,43,97,89,39,57,93,83,70,39,79,80,5,25,30,89,66
income11,93,98,9,9,23,99,64,36,59,75,16,75,56,49,30,94,98,28,34,47
income12,99,8,76,9,22,90,22,90,48,23,58,11,49,37,5,22,24,23,33,33

In [15]:
# Добавляем столбец с коэффициентом вариации для каждого товара

df['coef_var'] = df_t.iloc[1:, :].std() / df_t.iloc[1:, :].mean()
df

,product,income1,income2,income3,income4,income5,income6,income7,income8,income9,income10,income11,income12,coef_var
0,product1,90,56,78,76,79,76,89,78,90,67,93,99,0.148437
1,product2,1,45,7,68,98,65,4,32,56,78,98,8,0.773230
2,product3,45,67,54,43,45,56,76,58,65,32,9,76,0.366898
3,product4,9,9,9,9,9,9,9,9,9,9,9,9,0.000000
4,product5,23,43,23,27,48,36,34,27,19,43,23,22,0.319902
5,product6,98,99,90,97,90,98,97,99,97,97,99,90,0.038102
6,product7,56,78,76,34,65,78,29,83,46,89,64,22,0.376319
7,product8,48,6,64,4,74,61,40,96,23,39,36,90,0.615883
8,product9,55,39,81,93,69,40,41,19,36,57,59,48,0.388358
9,product10,54,45,50,38,52,80,29,54,12,93,75,23,0.470551
10,product11,30,25,25,96,79,91,9,67,10,83,16,58,0.677300
11,product12,99,74,53,68,81,83,17,25,13,70,75,11,0.556612
12,product13,23,95,79,41,77,99,97,11,16,39,56,49,0.563691
13,product14,93,98,68,95,32,22,53,86,53,79,49,37,0.414109
14,product15,93,4,98,81,10,92,29,47,15,80,30,5,0.773132
15,product16,66,26,75,9,86,41,17,40,90,5,94,22,0.693518
16,product17,98,38,32,56,68,44,69,51,71,25,98,24,0.452955
17,product18,25,29,30,15,40,43,25,27,20,30,28,23,0.276397
18,product19,13,7,56,52,60,72,54,8,9,89,34,33,0.677054
19,product20,24,91,47,97,23,59,32,27,9,66,47,33,0.594076

In [16]:
# Добавляем столбец с группой товара. 
# Присваиваем позициям ту или иную группу: до 10% - группу X, до 25% - Y, остальное – Z.

df.loc[df.coef_var >= 0.25, 'XYZ-group'] = 'Z'
df.loc[df.coef_var < 0.25, 'XYZ-group'] = 'Y'
df.loc[df.coef_var < 0.1, 'XYZ-group'] = 'X'
df

,product,income1,income2,income3,income4,income5,income6,income7,income8,income9,income10,income11,income12,coef_var,XYZ-group
0,product1,90,56,78,76,79,76,89,78,90,67,93,99,0.148437,Y
1,product2,1,45,7,68,98,65,4,32,56,78,98,8,0.773230,Z
2,product3,45,67,54,43,45,56,76,58,65,32,9,76,0.366898,Z
3,product4,9,9,9,9,9,9,9,9,9,9,9,9,0.000000,X
4,product5,23,43,23,27,48,36,34,27,19,43,23,22,0.319902,Z
5,product6,98,99,90,97,90,98,97,99,97,97,99,90,0.038102,X
6,product7,56,78,76,34,65,78,29,83,46,89,64,22,0.376319,Z
7,product8,48,6,64,4,74,61,40,96,23,39,36,90,0.615883,Z
8,product9,55,39,81,93,69,40,41,19,36,57,59,48,0.388358,Z
9,product10,54,45,50,38,52,80,29,54,12,93,75,23,0.470551,Z
10,product11,30,25,25,96,79,91,9,67,10,83,16,58,0.677300,Z
11,product12,99,74,53,68,81,83,17,25,13,70,75,11,0.556612,Z
12,product13,23,95,79,41,77,99,97,11,16,39,56,49,0.563691,Z
13,product14,93,98,68,95,32,22,53,86,53,79,49,37,0.414109,Z
14,product15,93,4,98,81,10,92,29,47,15,80,30,5,0.773132,Z
15,product16,66,26,75,9,86,41,17,40,90,5,94,22,0.693518,Z
16,product17,98,38,32,56,68,44,69,51,71,25,98,24,0.452955,Z
17,product18,25,29,30,15,40,43,25,27,20,30,28,23,0.276397,Z
18,product19,13,7,56,52,60,72,54,8,9,89,34,33,0.677054,Z
19,product20,24,91,47,97,23,59,32,27,9,66,47,33,0.594076,Z

In [17]:
# Добавляем столбец с доходом за все месяцы для каждого товара

df['income'] = df_t.iloc[1:, :].sum()
df

,product,income1,income2,income3,income4,income5,income6,income7,income8,income9,income10,income11,income12,coef_var,XYZ-group,income
0,product1,90,56,78,76,79,76,89,78,90,67,93,99,0.148437,Y,971
1,product2,1,45,7,68,98,65,4,32,56,78,98,8,0.773230,Z,560
2,product3,45,67,54,43,45,56,76,58,65,32,9,76,0.366898,Z,626
3,product4,9,9,9,9,9,9,9,9,9,9,9,9,0.000000,X,108
4,product5,23,43,23,27,48,36,34,27,19,43,23,22,0.319902,Z,368
5,product6,98,99,90,97,90,98,97,99,97,97,99,90,0.038102,X,1151
6,product7,56,78,76,34,65,78,29,83,46,89,64,22,0.376319,Z,720
7,product8,48,6,64,4,74,61,40,96,23,39,36,90,0.615883,Z,581
8,product9,55,39,81,93,69,40,41,19,36,57,59,48,0.388358,Z,637
9,product10,54,45,50,38,52,80,29,54,12,93,75,23,0.470551,Z,605
10,product11,30,25,25,96,79,91,9,67,10,83,16,58,0.677300,Z,589
11,product12,99,74,53,68,81,83,17,25,13,70,75,11,0.556612,Z,669
12,product13,23,95,79,41,77,99,97,11,16,39,56,49,0.563691,Z,682
13,product14,93,98,68,95,32,22,53,86,53,79,49,37,0.414109,Z,765
14,product15,93,4,98,81,10,92,29,47,15,80,30,5,0.773132,Z,584
15,product16,66,26,75,9,86,41,17,40,90,5,94,22,0.693518,Z,571
16,product17,98,38,32,56,68,44,69,51,71,25,98,24,0.452955,Z,674
17,product18,25,29,30,15,40,43,25,27,20,30,28,23,0.276397,Z,335
18,product19,13,7,56,52,60,72,54,8,9,89,34,33,0.677054,Z,487
19,product20,24,91,47,97,23,59,32,27,9,66,47,33,0.594076,Z,555

In [18]:
# Сортируем данные по убыванию суммарного дохода

df = df.sort_values('income', ascending=False)
df

,product,income1,income2,income3,income4,income5,income6,income7,income8,income9,income10,income11,income12,coef_var,XYZ-group,income
5,product6,98,99,90,97,90,98,97,99,97,97,99,90,0.038102,X,1151
0,product1,90,56,78,76,79,76,89,78,90,67,93,99,0.148437,Y,971
13,product14,93,98,68,95,32,22,53,86,53,79,49,37,0.414109,Z,765
6,product7,56,78,76,34,65,78,29,83,46,89,64,22,0.376319,Z,720
12,product13,23,95,79,41,77,99,97,11,16,39,56,49,0.563691,Z,682
16,product17,98,38,32,56,68,44,69,51,71,25,98,24,0.452955,Z,674
11,product12,99,74,53,68,81,83,17,25,13,70,75,11,0.556612,Z,669
8,product9,55,39,81,93,69,40,41,19,36,57,59,48,0.388358,Z,637
2,product3,45,67,54,43,45,56,76,58,65,32,9,76,0.366898,Z,626
9,product10,54,45,50,38,52,80,29,54,12,93,75,23,0.470551,Z,605
10,product11,30,25,25,96,79,91,9,67,10,83,16,58,0.677300,Z,589
14,product15,93,4,98,81,10,92,29,47,15,80,30,5,0.773132,Z,584
7,product8,48,6,64,4,74,61,40,96,23,39,36,90,0.615883,Z,581
15,product16,66,26,75,9,86,41,17,40,90,5,94,22,0.693518,Z,571
1,product2,1,45,7,68,98,65,4,32,56,78,98,8,0.773230,Z,560
19,product20,24,91,47,97,23,59,32,27,9,66,47,33,0.594076,Z,555
18,product19,13,7,56,52,60,72,54,8,9,89,34,33,0.677054,Z,487
4,product5,23,43,23,27,48,36,34,27,19,43,23,22,0.319902,Z,368
17,product18,25,29,30,15,40,43,25,27,20,30,28,23,0.276397,Z,335
3,product4,9,9,9,9,9,9,9,9,9,9,9,9,0.000000,X,108

In [19]:
# Считаем суммарный доход

total_income = df['income'].sum()
total_income

12238

In [20]:
# Добавляем столбец с долей дохода от каждого товара

df['share'] = df['income']/total_income
df

,product,income1,income2,income3,income4,income5,income6,income7,income8,income9,income10,income11,income12,coef_var,XYZ-group,income,share
5,product6,98,99,90,97,90,98,97,99,97,97,99,90,0.038102,X,1151,0.094051
0,product1,90,56,78,76,79,76,89,78,90,67,93,99,0.148437,Y,971,0.079343
13,product14,93,98,68,95,32,22,53,86,53,79,49,37,0.414109,Z,765,0.06251
6,product7,56,78,76,34,65,78,29,83,46,89,64,22,0.376319,Z,720,0.058833
12,product13,23,95,79,41,77,99,97,11,16,39,56,49,0.563691,Z,682,0.055728
16,product17,98,38,32,56,68,44,69,51,71,25,98,24,0.452955,Z,674,0.055074
11,product12,99,74,53,68,81,83,17,25,13,70,75,11,0.556612,Z,669,0.054666
8,product9,55,39,81,93,69,40,41,19,36,57,59,48,0.388358,Z,637,0.052051
2,product3,45,67,54,43,45,56,76,58,65,32,9,76,0.366898,Z,626,0.051152
9,product10,54,45,50,38,52,80,29,54,12,93,75,23,0.470551,Z,605,0.049436
10,product11,30,25,25,96,79,91,9,67,10,83,16,58,0.677300,Z,589,0.048129
14,product15,93,4,98,81,10,92,29,47,15,80,30,5,0.773132,Z,584,0.04772
7,product8,48,6,64,4,74,61,40,96,23,39,36,90,0.615883,Z,581,0.047475
15,product16,66,26,75,9,86,41,17,40,90,5,94,22,0.693518,Z,571,0.046658
1,product2,1,45,7,68,98,65,4,32,56,78,98,8,0.773230,Z,560,0.045759
19,product20,24,91,47,97,23,59,32,27,9,66,47,33,0.594076,Z,555,0.045351
18,product19,13,7,56,52,60,72,54,8,9,89,34,33,0.677054,Z,487,0.039794
4,product5,23,43,23,27,48,36,34,27,19,43,23,22,0.319902,Z,368,0.03007
17,product18,25,29,30,15,40,43,25,27,20,30,28,23,0.276397,Z,335,0.027374
3,product4,9,9,9,9,9,9,9,9,9,9,9,9,0.000000,X,108,0.008825

In [21]:
# Добавляем столбец с накопленной долей

df['accum_share'] = df['share'].cumsum()
df

,product,income1,income2,income3,income4,income5,income6,income7,income8,income9,income10,income11,income12,coef_var,XYZ-group,income,share,accum_share
5,product6,98,99,90,97,90,98,97,99,97,97,99,90,0.038102,X,1151,0.094051,0.094051
0,product1,90,56,78,76,79,76,89,78,90,67,93,99,0.148437,Y,971,0.079343,0.173394
13,product14,93,98,68,95,32,22,53,86,53,79,49,37,0.414109,Z,765,0.06251,0.235905
6,product7,56,78,76,34,65,78,29,83,46,89,64,22,0.376319,Z,720,0.058833,0.294738
12,product13,23,95,79,41,77,99,97,11,16,39,56,49,0.563691,Z,682,0.055728,0.350466
16,product17,98,38,32,56,68,44,69,51,71,25,98,24,0.452955,Z,674,0.055074,0.40554
11,product12,99,74,53,68,81,83,17,25,13,70,75,11,0.556612,Z,669,0.054666,0.460206
8,product9,55,39,81,93,69,40,41,19,36,57,59,48,0.388358,Z,637,0.052051,0.512257
2,product3,45,67,54,43,45,56,76,58,65,32,9,76,0.366898,Z,626,0.051152,0.563409
9,product10,54,45,50,38,52,80,29,54,12,93,75,23,0.470551,Z,605,0.049436,0.612845
10,product11,30,25,25,96,79,91,9,67,10,83,16,58,0.677300,Z,589,0.048129,0.660974
14,product15,93,4,98,81,10,92,29,47,15,80,30,5,0.773132,Z,584,0.04772,0.708694
7,product8,48,6,64,4,74,61,40,96,23,39,36,90,0.615883,Z,581,0.047475,0.756169
15,product16,66,26,75,9,86,41,17,40,90,5,94,22,0.693518,Z,571,0.046658,0.802827
1,product2,1,45,7,68,98,65,4,32,56,78,98,8,0.773230,Z,560,0.045759,0.848586
19,product20,24,91,47,97,23,59,32,27,9,66,47,33,0.594076,Z,555,0.045351,0.893937
18,product19,13,7,56,52,60,72,54,8,9,89,34,33,0.677054,Z,487,0.039794,0.933731
4,product5,23,43,23,27,48,36,34,27,19,43,23,22,0.319902,Z,368,0.03007,0.963801
17,product18,25,29,30,15,40,43,25,27,20,30,28,23,0.276397,Z,335,0.027374,0.991175
3,product4,9,9,9,9,9,9,9,9,9,9,9,9,0.000000,X,108,0.008825,1.0

In [22]:
# Добавляем столбец с группой товара. 
# Присваиваем позициям ту или иную группу: до 80% - группу А, до 95% - В, остальное – С.

df.loc[df.accum_share <= 1, 'ABC-group'] = 'C'
df.loc[df.accum_share < 0.95, 'ABC-group'] = 'B'
df.loc[df.accum_share < 0.8, 'ABC-group'] = 'A'
df

,product,income1,income2,income3,income4,income5,income6,income7,income8,income9,income10,income11,income12,coef_var,XYZ-group,income,share,accum_share,ABC-group
5,product6,98,99,90,97,90,98,97,99,97,97,99,90,0.038102,X,1151,0.094051,0.094051,A
0,product1,90,56,78,76,79,76,89,78,90,67,93,99,0.148437,Y,971,0.079343,0.173394,A
13,product14,93,98,68,95,32,22,53,86,53,79,49,37,0.414109,Z,765,0.06251,0.235905,A
6,product7,56,78,76,34,65,78,29,83,46,89,64,22,0.376319,Z,720,0.058833,0.294738,A
12,product13,23,95,79,41,77,99,97,11,16,39,56,49,0.563691,Z,682,0.055728,0.350466,A
16,product17,98,38,32,56,68,44,69,51,71,25,98,24,0.452955,Z,674,0.055074,0.40554,A
11,product12,99,74,53,68,81,83,17,25,13,70,75,11,0.556612,Z,669,0.054666,0.460206,A
8,product9,55,39,81,93,69,40,41,19,36,57,59,48,0.388358,Z,637,0.052051,0.512257,A
2,product3,45,67,54,43,45,56,76,58,65,32,9,76,0.366898,Z,626,0.051152,0.563409,A
9,product10,54,45,50,38,52,80,29,54,12,93,75,23,0.470551,Z,605,0.049436,0.612845,A
10,product11,30,25,25,96,79,91,9,67,10,83,16,58,0.677300,Z,589,0.048129,0.660974,A
14,product15,93,4,98,81,10,92,29,47,15,80,30,5,0.773132,Z,584,0.04772,0.708694,A
7,product8,48,6,64,4,74,61,40,96,23,39,36,90,0.615883,Z,581,0.047475,0.756169,A
15,product16,66,26,75,9,86,41,17,40,90,5,94,22,0.693518,Z,571,0.046658,0.802827,B
1,product2,1,45,7,68,98,65,4,32,56,78,98,8,0.773230,Z,560,0.045759,0.848586,B
19,product20,24,91,47,97,23,59,32,27,9,66,47,33,0.594076,Z,555,0.045351,0.893937,B
18,product19,13,7,56,52,60,72,54,8,9,89,34,33,0.677054,Z,487,0.039794,0.933731,B
4,product5,23,43,23,27,48,36,34,27,19,43,23,22,0.319902,Z,368,0.03007,0.963801,C
17,product18,25,29,30,15,40,43,25,27,20,30,28,23,0.276397,Z,335,0.027374,0.991175,C
3,product4,9,9,9,9,9,9,9,9,9,9,9,9,0.000000,X,108,0.008825,1.0,C

In [23]:
# Записываем результирующую таблицу в excel-файл

df.to_excel('ABC-XYZ output.xlsx')